FROM koosiedemoer/netty-tcnative-alpine

COPY hadleticket-api.jar app.jar
COPY application.properties app.properties

#RUN apk update && apk add bash && apk add nano

ENTRYPOINT ["java","-jar","/app.jar", "--spring.config.location=/app.properties"]